name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["x86-64-avx2"]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}.exe largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v3
        with:
          name: fairy-stockfish
          path: src/fairy-stockfish*.exe
